[project]
name = "kg-traversal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-openai>=1.1.0",
    "langgraph>=1.0.4",
    "networkx>=3.6",
]
